version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: laravel_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel_network

  web:
    image: nginx:latest
    container_name: laravel_web
    volumes:
      - ./src:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - laravel_network

  db:
    image: mariadb:latest
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - laravel_network

networks:
  laravel_network:
